### ISSUE TITLE
Set `href` of Github profile to the Github repository project

### ISSUE THREAD

**Issue by czerkies** [czerkies/romanczerkies.31#120]
New `href` value : //github.com/czerkies/romanczerkies.31

**Comment by VISHALDINESH** [comment]
@czerkies I can work on this. Assign me . Thanks

**Comment by VISHALDINESH** [comment]
Ok should I need to put my GitHub profile link where `id is Github `

**Comment by czerkies** [comment]
@Vishal-Parasram Could you work and commit from the branch linked to the Issue ?

Branch : https://github.com/czerkies/romanczerkies.31/tree/121-v31130

**Comment by Vishal-Parasram** [comment]
@czerkies can you describe a little bit.

**Comment by czerkies** [comment]
@Vishal-Parasram On the right column you have the Development section with the branch linked to the issue.
So you have to checkout on it then work en pull request from it 🙂

**Comment by Vishal-Parasram** [comment]
@czerkies Hi!

Get this 

Version | Date
-- | --
31.12.0 | 31/03/2023
31.11.0 | 09/01/2023
31.10.0 | 18/11/2022
31.9.0 | 23/09/2022
31.8.0 | 06/06/2022

after clicking in version 31.12.0 get following things. 


</body>
</html>
Media Queries Level 4 https://github.com/czerkies/romanczerkies.31/issues/59
Update keys and add Id key in the manifest.webmanifest https://github.com/czerkies/romanczerkies.31/issues/107
Add :focus-visible selector in nav to improve the behavior consistency https://github.com/czerkies/romanczerkies.31/issues/110
Add text-decoration-skip-ink: all; on a:any-link to enhance legibility https://github.com/czerkies/romanczerkies.31/issues/111
Add dir="auto" property in html element to let the user agent parses the characters when translation asked https://github.com/czerkies/romanczerkies.31/issues/113
Use Container query length units to enhance the nav element behavior https://github.com/czerkies/romanczerkies.31/issues/115
Bring consistency in assets name inside head element https://github.com/czerkies/romanczerkies.31/issues/116

should I need to work on this. Version	Date
[31.12.0](https://github.com/czerkies/romanczerkies.31/releases/tag/v31.12.0)	31/03/2023
[31.11.0](https://github.com/czerkies/romanczerkies.31/releases/tag/v31.11.0)	09/01/2023
[31.10.0](https://github.com/czerkies/romanczerkies.31/releases/tag/v31.10.0)	18/11/2022
[31.9.0](https://github.com/czerkies/romanczerkies.31/releases/tag/v31.9.0)	23/09/2022
[31.8.0](https://github.com/czerkies/romanczerkies.31/releases/tag/v31.8.0)	06/06/2022

**Comment by czerkies** [comment]
Yes and on Git, you have to checkout (`git checkout 121-v31130`) and work on that branch.

**Comment by Vishal-Parasram** [comment]
Ok let me try.

**Comment by czerkies** [comment]
@Vishal-Parasram Do you need help?

**Comment by Vishal-Parasram** [comment]
@czerkies yes.

**Comment by czerkies** [comment]
@Vishal-Parasram Yes, as mentioned in the first comment (it was right on your first Pull Request).

**Comment by Vishal-Parasram** [comment]
Ok I will create a PR.

**Comment by Vishal-Parasram** [comment]
@czerkies Review requested.

**Comment by Vishal-Parasram** [comment]
@czerkies Did you check it.

**Comment by czerkies** [comment]
@Vishal-Parasram It's perfect, thanks a lot for your contribution !
https://github.com/czerkies/romanczerkies.31/commit/c385d62097eceebd0301e58e60f9021249915d89
#123

**Comment by czerkies** [comment]
Update `title` property for the new `href` property.
