### ISSUE TITLE
Enhance `clamp()` adaptive behavior for different Writing Modes in using logical properties with viewport units

### ISSUE THREAD

**Issue by czerkies** [czerkies/romanczerkies.31#138]
- [x] `vw` → `vi` or `svi`
- [x] `vh` → `vb` or `svb`
- `clamp()` function used to adaptative spacing.

#137

**Comment by czerkies** [comment]
Following the needed of consistency behavior and a layout more corresponding to the ICB sizes, the viewport-units chosen is `sbv` and `svi`.

**Comment by czerkies** [comment]
@Vishal-Parasram You can take this Issue.

**Comment by Vishal-Parasram** [comment]
Thanks for assigning me.
